import * as React from 'react'
import { extractCodeFromSnippet } from '../../../utils/snippets'
import { MarkDownContext } from '../../MDView'
import codepen from './codepen.svg'
import './index.css'
import CodepenPrefill from 'react-codepen-prefill'

const CodePenRenderer: React.FC<{ value: string }> = ({ value, children }) => {
  const { snippet } = React.useContext(MarkDownContext)
  const [meta, setCodePenMeta] = React.useState({ css: '', js: '', html: '' })

  React.useEffect(() => {
    const cssCode = extractCodeFromSnippet(snippet, 'css')
    const jsCode = extractCodeFromSnippet(snippet, 'js')
    const htmlCode = extractCodeFromSnippet(snippet, 'html')
    setCodePenMeta({ css: cssCode, js: jsCode, html: htmlCode })
  }, [snippet])
  return (
    <>
      {value === 'Demo' && (
        <>
          <h4>{children}</h4>
          <span className="codepen-prefill-toolbar">
            <CodepenPrefill
              label={
                <>
                  <img src={codepen} alt="CodePen Icon" />
                  <span>Edit on CodePen</span>
                </>
              }
              className="markdown-renderer-codepenButton"
              target="_blank"
              title="30 Seconds of Knowledge - Snippet"
              description="A snippet generated by 30 Seconds of Knowledge"
              js={meta.js}
              css={meta.css}
              htmlPreProcessor="slim"
              html={meta.html}
              editors="111"
            />
          </span>
          <div className={`markdown-renderer-demoContainer`}>
            {/* <span className={`${CLASS}-jsNotif`}>
              <strong>WARNING:</strong> This snippet uses Javascript! Because of security issues, we are not able to run
              Javascript inside this preview. To see the intended behavior, please open the snippet on Codepen!
            </span> */}

            <iframe
              className={`markdown-renderer-snippetPreviewRenderer`}
              title={'30 Seconds of Knowledge - Demo'}
              sandbox="allow-scripts"
              allowFullScreen={true}
              srcDoc={`<html>
                        <head>
                            ${meta.css && `<style>${meta.css}</style>`}
                        </head>
                        <body>
                            ${meta.html || ''}
                        </body>
                    </html>`}
            />
          </div>
        </>
      )}
      {value !== 'Demo' && <h4>{children}</h4>}
    </>
  )
}

export default CodePenRenderer
